# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='sample',
  syntax='proto2',
  serialized_pb=_b('\n\x0csample.proto\x12\x06sample\"n\n\x05\x42lock\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x17\n\x0c\x61vailability\x18\x03 \x02(\x05:\x01\x30\x12\x0f\n\x07unicode\x18\x04 \x02(\t\x12\x0f\n\x04type\x18\x05 \x02(\x05:\x01\x30\x12\x10\n\x08place_id\x18\x06 \x01(\x05\"\xf9\x01\n\rParking_place\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07unicode\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x17\n\x0c\x61vailability\x18\x04 \x02(\x05:\x01\x30\x12\x13\n\x04rule\x18\x05 \x02(\t:\x05\x32\x34hrs\x12\x17\n\x04lang\x18\x06 \x02(\x02:\t11.546548\x12\x16\n\x03lat\x18\x07 \x02(\x02:\t13.657803\x12\x0f\n\x04type\x18\x08 \x02(\x05:\x01\x30\x12\x14\n\x08\x61utoexit\x18\t \x02(\t:\x02No\x12\x18\n\tcreatedby\x18\n \x01(\t:\x05\x41\x64min\x12\x1d\n\x06\x62locks\x18\x0b \x03(\x0b\x32\r.sample.Block')
)




_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='sample.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sample.Block.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='sample.Block.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='availability', full_name='sample.Block.availability', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unicode', full_name='sample.Block.unicode', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='sample.Block.type', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='place_id', full_name='sample.Block.place_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=134,
)


_PARKING_PLACE = _descriptor.Descriptor(
  name='Parking_place',
  full_name='sample.Parking_place',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sample.Parking_place.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unicode', full_name='sample.Parking_place.unicode', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='sample.Parking_place.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='availability', full_name='sample.Parking_place.availability', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rule', full_name='sample.Parking_place.rule', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("24hrs").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lang', full_name='sample.Parking_place.lang', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(11.546548),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='sample.Parking_place.lat', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(13.657803),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='sample.Parking_place.type', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='autoexit', full_name='sample.Parking_place.autoexit', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("No").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createdby', full_name='sample.Parking_place.createdby', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Admin").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='sample.Parking_place.blocks', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=386,
)

_PARKING_PLACE.fields_by_name['blocks'].message_type = _BLOCK
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['Parking_place'] = _PARKING_PLACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.Block)
  ))
_sym_db.RegisterMessage(Block)

Parking_place = _reflection.GeneratedProtocolMessageType('Parking_place', (_message.Message,), dict(
  DESCRIPTOR = _PARKING_PLACE,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.Parking_place)
  ))
_sym_db.RegisterMessage(Parking_place)


# @@protoc_insertion_point(module_scope)
